// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/mantil.go"
	"github.com/mantil-team/demo-chat/api/chat"
)

func main() {
	var api = chat.New()
	mantil.LambdaHandler(api)
}
